### ISSUE TITLE
unable to run k-bench for GKE clusters

### ISSUE THREAD

**Issue by vdesikanvmware** [vmware-tanzu/k-bench#39]
Running in to the following issue while running k-bench against GKE.
`tceuser@tkg-cli-client:~/k-bench$ ./run.sh -r gke_notap -t all
Running test command_in_container_predicate and results redirected to "./results_gke_notap_15-Dec-2021-08-58-54-am/command_in_container_predicate"
Starting benchmark, writing logs to results_gke_notap_15-Dec-2021-08-58-54-am/command_in_container_predicate/kbench.log... 
Running workload, please check kbench log for details... 
panic: no Auth Provider found for name "gcp"

goroutine 1 [running]:
k-bench/util.Run(0xc000206800, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /root/go/src/k-bench/util/testdriver.go:164 +0x22f1
main.main()
        /root/go/src/k-bench/cmd/kbench.go:193 +0xe76
Running test command_outside_container_and_resource_predicate and results redirected to "./results_gke_notap_15-Dec-2021-08-58-54-am/command_outside_container_and_resource_predicate"
Starting benchmark, writing logs to results_gke_notap_15-Dec-2021-08-58-54-am/command_outside_container_and_resource_predicate/kbench.log... 
Running workload, please check kbench log for details... 
panic: no Auth Provider found for name "gcp"

goroutine 1 [running]:
k-bench/util.Run(0xc00023a800, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /root/go/src/k-bench/util/testdriver.go:164 +0x22f1
main.main()
        /root/go/src/k-bench/cmd/kbench.go:193 +0xe76
Running test cp_heavy_12client and results redirected to "./results_gke_notap_15-Dec-2021-08-58-54-am/cp_heavy_12client"
Starting benchmark, writing logs to results_gke_notap_15-Dec-2021-08-58-54-am/cp_heavy_12client/kbench.log... 
Running workload, please check kbench log for details... 
panic: no Auth Provider found for name "gcp"

goroutine 1 [running]:
k-bench/util.Run(0xc0001f2800, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /root/go/src/k-bench/util/testdriver.go:164 +0x22f1
main.main()
        /root/go/src/k-bench/cmd/kbench.go:193 +0xe76
`

**Comment by vdesikanvmware** [comment]
Any updates on this issue?

**Comment by vdesikanvmware** [comment]
Is there a fix planned for this issue?

**Comment by krizh1990** [comment]
Add this line in headers of testdriver.go and that fixed the issue

_ "k8s.io/client-go/plugin/pkg/client/auth/gcp"

**Comment by vipinms2** [comment]
I have added "k8s.io/client-go/plugin/pkg/client/auth/gcp" in the header as
```
import (
        "k8s.io/client-go/plugin/pkg/client/auth/gcp"
        "bytes"
        "io/ioutil"
        "k-bench/manager"
        "k8s.io/client-go/dynamic"
        "reflect"
        "strings"
        "sync"
        "time"

        log "github.com/sirupsen/logrus"
        metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
        "k8s.io/client-go/kubernetes"
        restclient "k8s.io/client-go/rest"
        //"k8s.io/client-go/tools/clientcmd"
        "k-bench/perf_util"
        "os"
        "os/exec"
        "path/filepath"
)
```

I am facing the below error while performing ./run.sh -t dp_fio:
```
./run.sh -t dp_fio
Running test dp_fio and results redirected to "./results_run_05-May-2022-12-14-18-pm/dp_fio"
W0505 12:14:18.254344  150342 gcp.go:120] WARNING: the gcp auth plugin is deprecated in v1.22+, unavailable in v1.25+; use gcloud instead.
To learn more, consult https://cloud.google.com/blog/products/containers-kubernetes/kubectl-auth-changes-in-gke
Error from server (NotFound): error when creating "./config/dp_fio/fio_pvc.yaml": namespaces "kbench-pod-namespace" not found
Starting benchmark, writing logs to results_run_05-May-2022-12-14-18-pm/dp_fio/kbench.log... 
Running workload, please check kbench log for details... 
panic: no Auth Provider found for name "gcp"

goroutine 1 [running]:
k-bench/util.Run(0xc000222600, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/root/go/src/k-bench/util/testdriver.go:164 +0x22f1
main.main()
	/root/go/src/k-bench/cmd/kbench.go:195 +0xdcd
```

**Comment by satishsudini** [comment]
Missing _ in the k8s.io/client-go/plugin/pkg/client/auth/gcp .Adding this in test driver resolved the issue 
import (
  _ "k8s.io/client-go/plugin/pkg/client/auth/gcp"
	"bytes"
	"io/ioutil"
	"k-bench/manager"
	"k8s.io/client-go/dynamic"
	"reflect"
	"strings"
	"sync"
	"time"
